#!/usr/bin/env bash
# Configure Ubuntu server as follows:
#   - facebook.com resolves to 8.8.8.8
#   - localhost resolves to 127.0.0.2

echo "127.0.0.2		localhost" > ~/hosts.new
cp /etc/hosts ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
